#!/bin/bash

# Get Ubuntu codename, e.g. jammy, dapper, warty, etc.
if [[ -r /etc/os-release ]]; then
    . /etc/os-release
    if [[ $ID = ubuntu ]]; then
        echo "Running $UBUNTU_CODENAME"
    else
        echo "Not running an Ubuntu distribution. ID=$ID, VERSION=$VERSION"
    fi
else
    echo "Not running a distribution with /etc/os-release available"
fi

# Canonical (used to) think my home IP is in the US, so fix sources.list
# sudo sed -i -e 's/us.archive.ubuntu.com/gb.archive.ubuntu.com/g' /etc/apt/sources.list

# Install bitwarden-cli
sudo snap install bw

# Login
if bw login --check ; then
  echo "BitWarden is logged in."
  if bw_unlock=$(bw unlock | grep 'export') ; then
    eval "${bw_unlock:2}"
  else
    echo "Failed to unlock BitWarden. Wrong password?. Try again."
    exit 1
  fi
elif bw_login=$(bw login | grep 'export') ; then
  # Log in to BitWarden CLI (ignore '$ ' that precedes export command)
  eval "${bw_login:2}"
else
  echo "Failed to login to BitWarden. Start again."
  exit 1
fi

# Get id_rsa and id_rsa.pub from BW
echo "Restore SSH keys..."
bw get notes c8c5dca7-aad6-4bd7-8df1-af29010dbf43 > ~/.ssh/id_rsa.pub
chmod 600 ~/.ssh/id_rsa.pub
bw get notes aafebb4e-10a3-45bf-9f50-af29010d7a59 > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

# Get backup key
export PASSPHRASE="$(bw get notes 'Backup: Dejadup Key')"
export FTP_PASSWORD="$(bw get password 'cloud.danbishop.uk Backups')"
# Restore backup to temporary location - Duplicity won't overwrite files by design
echo "Install deja-dup..."
sudo apt install -y deja-dup
echo "Restore user home directory backup..."
duplicity restore --force webdavs://dan@cloud.danbishop.uk/remote.php/webdav/Backup%20and%20Recovery/$HOSTNAME-$USER ~/tmp
# Move restored backup to home directory - and overwrite files
shopt -s dotglob
rsync -a ~/tmp/home/$USER/* ~
rm -rf ~/tmp

# Correct icon sizes
gsettings set org.gnome.nautilus.icon-view default-zoom-level 'medium'
# Show seconds on clock
gsettings set org.gnome.desktop.interface clock-show-seconds true
# Set desktop
gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/contest/$UBUNTU_CODENAME.xml"
# Enable dark mode
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-dark'

# Update apt
sudo apt-get update > /dev/null 2>&1
sudo apt-get dist-upgrade -y > /dev/null 2>&1

# Install apt packages (and flatpak)
sudo apt-get install -y deja-dup git curl ssh build-essential ruby ruby-dev flatpak

# Backup Settings
gsettings set org.gnome.DejaDup backend 'remote'
gsettings set org.gnome.DejaDup delete-after 182
gsettings set org.gnome.DejaDup exclude-list "['\$TRASH', '\$DOWNLOAD']"
gsettings set org.gnome.DejaDup full-backup-period 90
gsettings set org.gnome.DejaDup include-list "['$HOME/Videos', '$HOME/Templates', '$HOME/Public', '$HOME/Pictures', '$HOME/Obsidian', '$HOME/FiraxisLive', '$HOME/Documents', '$HOME/.vscode', '$HOME/.steam', '$HOME/.ssh', '$HOME/.gnupg', '$HOME/snap/firefox', '$HOME/snap/bitwarden', '$HOME/.local/share/keyrings', '$HOME/.config/goa-1.0']"
gsettings set org.gnome.DejaDup periodic true
gsettings set org.gnome.DejaDup periodic-period 7
gsettings set org.gnome.DejaDup prompt-check 'disabled'
gsettings set org.gnome.DejaDup tool 'duplicity'
gsettings set org.gnome.DejaDup.Drive folder "$HOSTNAME-$USER"
gsettings set org.gnome.DejaDup.Remote folder "$HOSTNAME-$USER"
gsettings set org.gnome.DejaDup.Remote uri 'davs://dan@cloud.danbishop.uk/remote.php/webdav/Backup%20and%20Recovery'

# Update snaps
sudo snap refresh

# Install VSCode
echo "Installing classic snaps..."
sudo snap install code --classic > /dev/null 2>&1

# Install other snaps
echo "Installing snaps..."
sudo snap install spotify kita slack openttd warzone2100 bitwarden signal-desktop > /dev/null 2>&1

# Install Zoom and keep it up to date
echo "Installing Zoom..."
sudo mkdir /opt/zoom-updater > /dev/null 2>&1
sudo cp ./files/zoom-update.sh /opt/zoom-updater/zoom-update.sh > /dev/null 2>&1
sudo chmod +x /opt/zoom-updater/zoom-update.sh > /dev/null 2>&1

sudo cp ./files/zoom-update.timer /etc/systemd/system/zoom-update.timer
sudo cp ./files/zoom-update.service /etc/systemd/system/zoom-update.service

sudo systemctl enable --now zoom-update.timer
sudo systemctl start zoom-update.service

# Install flatpak
echo "Installing flatpak..."
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Keep flatpaks up to date
sudo cat << EOF | sudo tee /etc/systemd/system/update-system-flatpaks.service
[Unit]
Description=Update system Flatpaks
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/flatpak update --assumeyes --noninteractive --system

[Install]
WantedBy=multi-user.target
EOF

sudo cat << EOF | sudo tee /etc/systemd/system/update-system-flatpaks.timer
[Unit]
Description=Update system Flatpaks daily

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF

sudo systemctl --system enable --now update-system-flatpaks.timer

# Install flatpaks
sudo flatpak install flathub com.github.iwalton3.jellyfin-media-player


# Set gitconfig
cp ./files/.gitconfig ~/

# Set dock favourites
gsettings set org.gnome.shell favorite-apps "['firefox_firefox.desktop', 'org.gnome.Nautilus.desktop', 'rhythmbox.desktop', 'snap-store_ubuntu-software.desktop', 'code_code.desktop', 'spotify_spotify.desktop', 'org.gnome.Terminal.desktop', 'Zoom.desktop']"

# Hide files
echo 'snap' >> ~/.hidden

# Create Projects folder if not exist
mkdir -p ~/Projects

# Clone some git repos
if [ ! -d "~/Projects/setup" ]; then
  git -C ~/Projects clone git@github.com:danbishop/setup.git
fi
if [ ! -d "~/Projects/setup" ]; then
  git -C ~/Projects clone git@github.com:danbishop/server-setup.git
fi
if [ ! -d "~/Projects/setup" ]; then
  git -C ~/Projects clone git@github.com:danbishop/danbishop.uk.git
fi

# Set webcams to use 50hz
echo "ACTION==\"add\", SUBSYSTEM==\"video4linux\", DRIVERS==\"uvcvideo\", RUN+=\"/usr/bin/v4l2-ctl --set-ctrl=power_line_frequency=1\"" > /etc/udev/rules.d/50-webcam-50hz.rules
udevadm trigger

# Finished
echo "All done 🙂"
